# This is a basic workflow to help you get started with Actions

name: Update-Pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * 0'

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
         activate-environment: maps
         
      - uses: s-weigand/setup-conda@v1
      - run: conda install pandas
      - run: conda install geopandas
#       - run: conda install tqdm
      - run: conda install urllib3
      - run: pip install sodapy
      - name: Conda info
        shell: bash -l {0}  # activate the conda environment
        run: |
          conda info
          conda list
      # Runs a single command using the runners shell
      - name: Run model script
        env:
         API_KEY: ${{ secrets.API_KEY }}
        run: |
          python data_clean.py # code-NB-3-ka.ipynb

